languages:
  python:
    enable: true
    package: "python311"
    tools:
      ruff:
        enable: true
        settings:
          config:
            line-length: 100
            exclude:
              - ".bzr"
              - ".direnv"
              - ".eggs"
              - ".git"
              - ".git-rewrite"
              - ".hg"
              - ".ipynb_checkpoints"
              - ".mypy_cache"
              - ".nox"
              - ".pants.d"
              - ".pyenv"
              - ".pytest_cache"
              - ".pytype"
              - ".ruff_cache"
              - ".svn"
              - ".tox"
              - ".venv"
              - ".vscode"
              - "__pypackages__"
              - "_build"
              - "buck-out"
              - "build"
              - "dist"
              - "node_modules"
              - "site-packages"
              - "venv"
            lint:
              select:
                - "E" # pycodestyle errors
                - "F" # pyflakes
                - "W" # pycodestyle warnings
                - "I" # isort
                - "N" # pep8-naming
                - "UP" # pyupgrade
                - "B" # flake8-bugbear
                - "C4" # flake8-comprehensions
                - "DTZ" # flake8-datetimez
                - "T10" # flake8-debugger
                - "ISC" # flake8-implicit-str-concat
                - "G" # flake8-logging-format
                - "PIE" # flake8-pie
                - "T20" # flake8-print
                - "PT" # flake8-pytest-style
                - "Q" # flake8-quotes
                - "RET" # flake8-return
                - "SIM" # flake8-simplify
                - "TID" # flake8-tidy-imports
                - "ARG" # flake8-unused-arguments
                - "PTH" # flake8-use-pathlib
                - "ERA" # eradicate
                - "PL" # pylint
                - "TRY" # tryceratops
                - "RUF" # ruff-specific rules
                - "FA" # from __future__ import annotations
                - "ICN" # import conventions
                - "TC" # type checking imports
                - "TD" # TODO comments
                - "NPY" # numpy-specific rules
                - "A" # shadowed builtins
                - "BLE" # catch-all exceptions
                - "S" # security issues
                - "FBT" # boolean traps
              ignore:
                - "ANN401"
                - "D"
                - "INP001"
                - "COM812"

  javascript:
    enable: true
    package: "nodejs_22"
    tools:
      yarn:
        enable: true
        package: "yarn-berry"
        settings:
          config:
            enableConstraintsChecks: false
      prettier:
        enable: true
        package: "prettierd"
        settings:
          config:
            trailingComma: "es5"
            tabWidth: 4
            semi: false
            singleQuote: true

shell_tools:
  aider:
    enable: true
    package: "aider-chat"
    settings:
      config:
        auto-commits: false
        dirty-commits: true
        auto-lint: true
        dark-mode: true
        light-mode: false
        cache-prompts: false
        code-theme: "solarized-dark"

  git:
    enable: true
    package: "gitFull"
    settings:
      user_name: "${GIT_USERNAME}"
      user_email: "${GIT_EMAIL}"
      gitignore:
        - __pycache__
        - .snow-blower
        - .sb
        - .env*
        - "!.env.example"
        - "result"
        - ".aider*"

services:
  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "sailmysql:/var/lib/mysql"
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
