languages:
  python:
    enabled: true
    package: "python311"
    tools:
      ruff:
        enabled: true
        settings:
          config:
            exclude:
              - ".bzr"
              - ".direnv"
              - ".eggs"
              - ".git"
              - ".git-rewrite"
              - ".hg"
              - ".ipynb_checkpoints"
              - ".mypy_cache"
              - ".nox"
              - ".pants.d"
              - ".pyenv"
              - ".pytest_cache"
              - ".pytype"
              - ".ruff_cache"
              - ".svn"
              - ".tox"
              - ".venv"
              - ".vscode"
              - "__pypackages__"
              - "_build"
              - "buck-out"
              - "build"
              - "dist"
              - "node_modules"
              - "site-packages"
              - "venv"
            select:
              - "ALL"
            ignore:
              - "ANN401"
              - "D"
              - "INP001"
            lint:
              extend-select:
                - "F" # Pyflakes rules
                - "W" # PyCodeStyle warnings
                - "E" # PyCodeStyle errors
                - "I" # Sort imports properly
                - "UP" # Warn if certain things can changed due to newer Python versions
                - "C4" # Catch incorrect use of comprehensions dict list etc
                - "FA" # Enforce from __future__ import annotations
                - "ISC" # Good use of string concatenation
                - "ICN" # Use common import conventions
                - "RET" # Good return practices
                - "SIM" # Common simplification rules
                - "TID" # Some good import practices
                - "TC" # Enforce importing certain types in a TYPE_CHECKING block
                - "PTH" # Use pathlib instead of os.path
                - "TD" # Be diligent with TODO comments
                - "NPY" # Some numpy-specific things
                - "A" # detect shadowed builtins
                - "BLE" # disallow catch-all exceptions
                - "S" # disallow things like "exec"; also restricts "assert" but I just NOQA it when I really need it
                - "COM" # enforce trailing comma rules
                - "DTZ" # require strict timezone manipulation with datetime
                - "FBT" # detect boolean traps
                - "N" # enforce naming conventions e.g. ClassName vs function_name

  javascript:
    enabled: true
    package: "nodejs_22"
    tools:
      yarn:
        enabled: true
        package: "yarn-berry"
      prettier:
        enabled: true
        package: "prettierd"
        config:
          settings:
            trailingComma: "es5"
            tabWidth: 4
            semi: false
            singleQuote: true

shell_tools:
  aider:
    enabled: true
    package: "aider-chat"
    settings:
      config:
        auto-commits: false
        dirty-commits: true
        auto-lint: true
        dark-mode: true
        light-mode: false
        cache-prompts: false
        code-theme: "solarized-dark"

  git:
    enabled: true
    package: "gitFull"
    settings:
      user_name: "use-the-fork"
      user_email: "23747916+use-the-fork@users.noreply.github.com"
      gitignore:
        - __pycache__
        - .snow-blower
        - .sb
        - .env*
        - "!.env.example"
        - "result"

services:
  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "sailmysql:/var/lib/mysql"
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
