services:
  dev:
    build:
      args:
        USER_GID: ${USER_GID}
        USER_UID: ${USER_UID}
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      USER_GID: ${USER_GID}
    tty: true
    volumes:
    - .:/workspace
    working_dir: /workspace
  npm-dev:
    build:
      args:
        USER_GID: ${USER_GID}
        USER_UID: ${USER_UID}
      context: .
      dockerfile: ./docker/Dockerfile
    command: npm run dev
    container_name: dev-npm-dev
    environment:
      USER_GID: ${USER_GID}
    tty: true
    volumes:
    - .:/workspace
    working_dir: /workspace
