["formatter.alejandra-lint"]
command = "alejandra"
includes = ["*.nix"]
priority = 0

["formatter.deadnix-lint"]
command = "deadnix"
includes = ["*.nix"]
options = ["--edit"]
priority = 0

["formatter.mdformat-format"]
command = "mdformat"
includes = ["*.md"]
priority = 100

["formatter.statix-lint"]
command = "statix-fix"
includes = ["*.nix"]
priority = 0
