services:
  dev:
    env_file:
    - path: ./../.env
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
        SNOW_BLOWER_CONFIG_PATH: ${SNOWBLOWER_CONFIG_PATH:-.devcontainer/snowblower-config.nix}
    volumes:
      - ..:/workspace:cached
      - ${HOME}/.ssh:/home/${REMOTE_USER_NAME:-code}/.ssh:ro
      - ../.snow-blower:/home/${REMOTE_USER_NAME:-code}/.snowblower:rw

volumes: 
  snow_blower:
