name: update-flake
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update Nix Flake
        run: |
          nix flake --accept-flake-config update
      - name: Build Snow Blower Shell
        run: |
          nix build --accept-flake-config .#devShells.x86_64-linux.default
      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit flake.lock -m "flake: bump inputs"
          git push
